# Generated by Django 4.2.5 on 2023-10-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='dia',
        ),
    ]
